baseURL = "http://ayseundmehmet.netlify.com/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Ayse und Mehmet"
[markup.goldmark.renderer]
unsafe = true
