[de]
contentDir = "content/deutsch"
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "De"
title = "Bigspring Hugo"
weight = 2
[en]
contentDir = "content/turkish"
copyright = "Design By [Atakan Köskeroglu](https://www.linkedin.com/in/atakan-koskeroglu/) Develop By [Atakan Köskeroglu](https://www.linkedin.com/in/atakan-koskeroglu/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "Tr"
title = "Ayse und Mehmet"
weight = 1
