[[footer_left]]
name = "Über uns"
url = "#"
[[footer_left]]
name = "Zeit & Ort"
url = "#"
[[footer_middle]]
name = "Beschränkungen"
url = "pricing"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Ort & Zeit"
url = "blog"
weight = 2
[[main]]
name = "Beschränkungen"
url = "pricing"
weight = 3
[[main]]
name = "Kontakt"
url = "contact"
weight = 4
[[main]]
name = "FAQ"
url = "faq"
weight = 5
