author = "Themefisher"
contact_form_action = "#"
description = "Informationen für Ayse und Mehmets Feierlichkeiten"
logo = "/images/ring-apple.png"
logo_width = "200px"
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/atakan-koskeroglu/"
title = "linkedin"
